---

version: 2

updates:

  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: monthly
    reviewers:
      - jkatzwinkel
  
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    reviewers:
      - jkatzwinkel

...
