---

name: citation

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: clone repo
        uses: actions/checkout@v2

      - name: validate CITATION.cff
        uses: LutrisEng/validate-cff@v1.0.0

...
