---

name: test

on: [push]  # yamllint disable-line

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: clone repo
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: install pipenv
        run: python -mpip install pipenv

      - name: cache-pipenv
        uses: actions/cache@v3
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: pipenv install --dev

      - name: run doctests
        run: pipenv run pytest --doctest-modules peret

      - name: run linter
        run: make lint

...
