---

name: validate-ths

on: workflow_dispatch

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: clone repo
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: install pipenv
        run: python -mpip install pipenv

      - name: cache-pipenv
        uses: actions/cache@v3
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: pipenv install

      - name: validate thesaurus
        run: pipenv run peret validate -f files/thesaurus.xml

      - name: validate thesaurus test fixture
        run: pipenv run peret validate -f test/files/thesaurus.xml

...
